[project]
name = "zotbrain"
version = "0.1.0"
requires-python = ">=3.13"

[tool.uv.sources]
zotero = { workspace = true }
server = { workspace = true }

[tool.uv.workspace]
members = ["backend/*"]

[tool.pyright]
venvPath = "."
venv = ".venv"
